# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  testproject : './src/antiboilerplate.tests/antiboilerplate.tests.csproj'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.101'

- script: dotnet restore $(testproject)
  displayName: 'Restore Nuget packages'

- script: dotnet build $(testproject) --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
