name: antiboilerplate CI

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"

  pull_request:
    branches: ["master"]
    paths:
      - "src/**"

  workflow_dispatch:

env:
  LIBRARY_PATH: "src/antiboilerplate/"
  TEST_PATH: "src/antiboilerplate.tests/"
  DOTNET_VERSION: "8.0"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Run tests
        run: dotnet test --configuration Release --logger trx --results-directory "TestResults"
        working-directory: "${{ env.TEST_PATH }}"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: "${{ env.TEST_PATH }}TestResults"
        if: ${{ always() }}
      - name: Bump version
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "${{ env.LIBRARY_PATH }}/antiboilerplate.csproj"
          version: bump-build
      - name: Publish
        shell: pwsh
        run: dotnet pack antiboilerplate.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg --output ./
        working-directory: "${{ env.LIBRARY_PATH }}"
      - name: Upload nuget
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: ${{ env.LIBRARY_PATH }}
      - run: |
          git config user.name "Vidar Kongsli"
          git config user.email "vidar@kongs.li"
          git add .
          git commit -m "Update project version to ${{ steps.update.outputs.newVersion }}"
          git push
        if: github.event_name == 'workflow_dispatch'
